# Generated by Django 4.1.2 on 2022-11-01 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 15, 37, 30, 329443, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
